version: '3'
services:
  backendApp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:v1
    container_name: EberBackend
    command: ["npm", "run", "dev"]
    ports: 
      - "4000:4000"
    networks:
      - app-network

  frontendApp:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:v1
    container_name: EberFrontend
    command: ["nginx", "-g", "daemon off;"]
    ports: 
      - "4200:80"
    depends_on:
      - backendApp
    networks:
      - app-network

networks:
    app-network:
        driver: bridge